"""phase 8: content strategies, idea embeddings

Revision ID: 4a1731dd243b
Revises: f425fea336e7
Create Date: 2026-08-31 14:54:43.090659

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4a1731dd243b"
down_revision: str | Sequence[str] | None = "f425fea336e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "content_strategies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_profile_id", sa.Integer(), nullable=False),
        sa.Column("best_topics", sa.JSON(), nullable=False),
        sa.Column("best_hook_types", sa.JSON(), nullable=False),
        sa.Column("recommended_duration", sa.JSON(), nullable=False),
        sa.Column("recommended_pacing", sa.Text(), nullable=False),
        sa.Column("recommended_posting_windows", sa.JSON(), nullable=False),
        sa.Column("avoid_patterns", sa.JSON(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("patterns", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_profile_id"],
            ["content_profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("ideas", sa.Column("embedding", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ideas", "embedding")
    op.drop_table("content_strategies")
    # ### end Alembic commands ###
